apiVersion: apps/v1
kind: Deployment
metadata:
  name: meme-generator-server-deployment
  labels:
    app: meme-generator
    type: meme-generator-server
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meme-generator
      type: meme-generator-server
      env: prod
  template:
    metadata:
      labels:
        app: meme-generator
        type: meme-generator-server
        env: prod
    spec:
      containers:
    spec:
      containers:
        - name: meme-generator-server
          image: meme-generator-server
          imagePullPolicy: Never
          ports:
            - containerPort: 8089
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: POSTGRES_DB
              value: memes
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: meme-generator-server-service
  labels:
    app: meme-generator
    type: meme-generator-server
    env: prod
spec:
  ports:
    - port: 8089
      targetPort: 8089
  selector:
    app: meme-generator
    type: meme-generator-server
    env: prod
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: meme-generator
    type: meme-generator-server
    env: prod
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy_cache_path: /data/nginx/cache
  name: meme-generator-server-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: meme-generator.ai
    http:
      paths:
      - backend:
          service:
            name: meme-generator-server-service
            port:
              number: 8089
        path: /memes
        pathType: Prefix
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: meme-generator-server-hpa
  labels:
    app: meme-generator
    type: meme-generator-server
    env: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: meme-generator-server-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
