apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: meme-generator
    type: postgres
    env: prod
data:
  POSTGRES_DB: memes
  POSTGRES_USER: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: meme-generator
    type: postgres
    env: prod
type: Opaque
data:
  POSTGRES_PASSWORD: cGFzc3dvcmQK
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: meme-generator
    type: postgres
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meme-generator
      type: postgres
      env: prod
  template:
    metadata:
      labels:
        app: meme-generator
        type: postgres
        env: prod
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          envFrom:
            - secretRef:
                name: postgres-secret
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    app: meme-generator
    type: postgres
    env: prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: meme-generator
    type: postgres
    env: prod
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: meme-generator
    type: postgres
    env: prod
  type: ClusterIP
---