apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  labels:
    app: meme-generator
    type: redis
    env: prod
data: 
  redis.conf: |
    # this is the redis config file.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: meme-generator
    type: redis
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meme-generator
      type: redis
      env: prod
  template:
    metadata:
      labels:
        app: meme-generator
        type: redis
        env: prod
    spec:
      containers:
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - mountPath: /usr/local/etc/redis/redis.conf
              name: redis-config
              subPath: redis.conf
      volumes:
        - name: redis-config
          configMap:
            name: redis-config
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: meme-generator
    type: redis
    env: prod
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: meme-generator
    type: redis
    env: prod
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: redis-hpa
  labels:
    app: meme-generator
    type: redis
    env: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: redis
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
