apiVersion: apps/v1
kind: Deployment
metadata:
  name: smtp-deployment
  labels:
    app: smtp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smtp
  template:
    metadata:
      labels:
        app: smtp
    spec:
      containers:
      - name: smtp
        image: smtp
        imagePullPolicy: Never
        ports:
        - containerPort: 2525
---
apiVersion: v1
kind: Service
metadata:
  name: smtp
spec:
  selector:
    app: smtp
  ports:
    - protocol: TCP
      port: 587
      targetPort: 2525