apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-smtp-deployment
  labels:
    app: node-smtp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-smtp
  template:
    metadata:
      labels:
        app: node-smtp
    spec:
      containers:
      - name: node-smtp
        image: node-smtp
        imagePullPolicy: Never
        ports:
        - containerPort: 2525
---
apiVersion: v1
kind: Service
metadata:
  name: node-smtp
spec:
  selector:
    app: node-smtp
  ports:
    - protocol: TCP
      port: 587
      targetPort: 2525